---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - yum:
        name: epel-release
    - rpm_key:
        key: https://packages.icinga.com/icinga.key
    - get_url:
        dest: /etc/yum.repos.d/ICINGA-release.repo
        url: https://packages.icinga.com/centos/ICINGA-release.repo
    - loop:
        - git
        - icinga2
        - icinga2-selinux
        - python3
        - python36-psutil
      yum:
        name: '{{ item }}'
    - copy:
        dest: /usr/lib64/nagios/plugins/
        src: check_random.py
    - file:
        path: /opt/Linuxfabrik
        state: directory
    - loop:
        - project: lib
          commit: 21542560ece9dffa2818fd16ee0495883271e7dc # 2023112901
        - project: monitoring-plugins
          commit: 096aa98a7d81d169d4492c00f94d0bc336b061dd # 2023112901
      git:
        dest: '/opt/Linuxfabrik/{{ item.project }}'
        repo: 'https://github.com/Linuxfabrik/{{ item.project }}.git'
        version: '{{ item.commit }}'

- hosts: 'all:!*master-1'
  become: true
  become_method: sudo
  become_user: icinga
  tasks:
    - shell: >-
        icinga2 node setup --zone {{ inventory_hostname
        }} --endpoint placeholder --cn {{ inventory_hostname
        }} --listen 0.0.0.0 --accept-config --accept-commands --disable-confd
      args:
        creates: /etc/icinga2/features-enabled/api.conf
    - shell: >-
        openssl req -new -nodes -subj /CN={{ inventory_hostname
        }} -key {{ inventory_hostname }}.key -out {{ inventory_hostname }}.csr
      args:
        chdir: /var/lib/icinga2/certs
        creates: '/var/lib/icinga2/certs/{{ inventory_hostname }}.csr'
    - fetch:
        dest: .download/csr.d/
        flat: true
        src: '/var/lib/icinga2/certs/{{ inventory_hostname }}.csr'

- hosts: '*master-1'
  become: true
  become_method: sudo
  become_user: icinga
  tasks:
    - copy:
        dest: /var/lib/icinga2/ansible-csr.d/
        src: .download/csr.d/
    - shell: >-
        icinga2 node setup --master --cn {{ inventory_hostname
        }} --listen 0.0.0.0 --accept-config --accept-commands --disable-confd
      args:
        creates: /etc/icinga2/features-enabled/api.conf
    - file:
        path: /var/lib/icinga2/ansible-cert.d
        owner: icinga
        state: directory
    - with_inventory_hostnames: 'all:!*master-1'
      shell: >-
        icinga2 pki sign-csr --csr ansible-csr.d/{{ item
        }}.csr --cert ansible-cert.d/{{ item }}.crt
      args:
        chdir: /var/lib/icinga2
        creates: '/var/lib/icinga2/ansible-cert.d/{{ item }}.crt'
    - fetch:
        dest: .download/
        flat: true
        src: /var/lib/icinga2/ca/ca.crt
    - with_inventory_hostnames: 'all:!*master-1'
      fetch:
        dest: .download/cert.d/
        flat: true
        src: '/var/lib/icinga2/ansible-cert.d/{{ item }}.crt'

- hosts: 'all:!*master-1'
  become: true
  become_method: sudo
  become_user: icinga
  tasks:
    - copy:
        dest: /var/lib/icinga2/certs/
        src: .download/ca.crt
    - copy:
        dest: /var/lib/icinga2/certs/
        src: '.download/cert.d/{{ inventory_hostname }}.crt'

- hosts: all
  become: true
  become_method: sudo
  tasks:
    - copy:
        dest: /etc/icinga2/
        src: zones.conf
    - service:
        name: icinga2
        state: started
        enabled: true
